name: Node CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'
          check-latest: true

      - name: npm install
        run: make install

      - name: Run linter
        run: make lint

      - name: Run test
        run: make test
